#
# Copyright (c) 2018 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#



# Enable the UART driver
CONFIG_UART_ASYNC_API=y

CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y

CONFIG_GPIO=y
CONFIG_SPI=y

# Make sure printk is printing to the UART console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

#2048
CONFIG_HEAP_MEM_POOL_SIZE=4096 

CONFIG_MAIN_STACK_SIZE=8192

CONFIG_BT=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_DEVICE_NAME="COSMIIC WirelessLink"
CONFIG_BT_DEVICE_APPEARANCE=833
CONFIG_BT_MAX_CONN=1
CONFIG_BT_MAX_PAIRED=5

# Enable the NUS service
CONFIG_BT_NUS=y
CONFIG_BT_NUS_SECURITY_ENABLED=y
CONFIG_BT_NUS_AUTHEN=y

# Enable bonding (change all back to y)
CONFIG_BT_SETTINGS=y
CONFIG_FLASH=y
CONFIG_FLASH_PAGE_LAYOUT=y
CONFIG_FLASH_MAP=y
CONFIG_NVS=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y


CONFIG_BT_SMP=y

# Configs for directed advertising
CONFIG_BT_FILTER_ACCEPT_LIST=y
CONFIG_BT_PRIVACY=y


# Enable DK LED and Buttons library
CONFIG_DK_LIBRARY=y

# This example requires more workqueue stack
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096  
#2048

# Config logger
CONFIG_LOG=y

#JML added
CONFIG_LOG_MODE_IMMEDIATE=n

CONFIG_LOG_BUFFER_SIZE=4096 
CONFIG_USE_SEGGER_RTT=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
CONFIG_LOG_PRINTK=n

CONFIG_LOG_MODE_OVERFLOW=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_PROCESS_THREAD_STACK_SIZE=4096


CONFIG_ASSERT=y
#CONFIG_LOG_DEFAULT_LEVEL=4

CONFIG_SENSOR=y
#CONFIG_ISM330IS=y  JML disabled because no ISM330IS driver loaded


#Fanstel board doesn't include NOR FLASH 
CONFIG_SPI_NOR=n
#Disabled low power
CONFIG_NRF_WIFI_LOW_POWER=n

CONFIG_PWM=y

CONFIG_LOG_SPEED=y

CONFIG_BT_LIM_ADV_TIMEOUT=60

CONFIG_POWEROFF=y
CONFIG_ADC=y
CONFIG_I2C=y

#CONFIG_NFCT_PINS_AS_GPIOS=y

##CONFIG_BOOTLOADER_MCUBOOT=y  ##now done with sysbuild

#SD CARD
CONFIG_DISK_ACCESS=y
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y
CONFIG_DISK_DRIVER_SDMMC=y
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_FATFS_MOUNT_MKFS=y
CONFIG_FS_FATFS_LFN_MODE_HEAP=y

CONFIG_WATCHDOG=y
CONFIG_WDT_DISABLE_AT_BOOT=y



#JML Added for Coil UART
CONFIG_UART_NRFX=y
CONFIG_NRFX_UARTE3=y
CONFIG_UART_3_INTERRUPT_DRIVEN=n
CONFIG_UART_3_ASYNC=y

#JML added for debugging
CONFIG_DEBUG_OPTIMIZATIONS=y
CONFIG_DEBUG_THREAD_INFO=y